### ISSUE TITLE
[Feature Request] add multiple tags to a provider 

### ISSUE THREAD

**Issue by KeizerDev** [zquestz/s#10]
Like Facebook or Youtube. It would be a lot easier to just type: `fb` or `yt`.

**Comment by zquestz** [comment]
We are going to have it complete based on best match.... facebook would be "f" unless there were other f providers. This should take care of that issue.

**Comment by zquestz** [comment]
See - https://github.com/zquestz/s/issues/7

**Comment by KeizerDev** [comment]
@zquestz Is it as a whole text match or just like the char order? If so, I do rather like `fb` than `face`.

**Comment by zquestz** [comment]
Right now it would just be the whole match... so facebook would be "f" right now as there is no other f providers... but as you stated, it would be "fa" if more providers were added. Maybe we could do this with tags? Tag the providers with other names, and you can reference by tag?

**Comment by zquestz** [comment]
I would also say, shell aliases can help a lot:

```
alias fb="s -p facebook"
```

**Comment by KeizerDev** [comment]
@zquestz Yeah, the tags is what I mean with aliases. We should look into it.

**Comment by zquestz** [comment]
Expansion has been added, we should see if that is sufficient. If not we can take a look at adding tags. =)

**Comment by KeizerDev** [comment]
@zquestz If you check out #23, you will see when doing `s movie -p kat` doesn't get anywhere. It would be pretty handy to get tags in that matter.

**Comment by zquestz** [comment]
Going to close this. Not going to do tags. I believe that partial completion and the shell completion for bash/zsh should be more than sufficient.
