### ISSUE TITLE
subl: command not found

### ISSUE THREAD

**Issue by ivanthemeh** [zquestz/s#115]
I installed this package using brew and I try to use it and it tells me ```bash: subl: command not found``` I havent installed sublime text or anything like that and I cant find an alias so Im not sure whats going on.

**Comment by KeizerDev** [comment]
It shouldn't ask for that, can you show me what you did, exactly. Like the install command and the run command.

**Comment by ivanthemeh** [comment]
brew install s-search

s puppies

**Comment by ivanthemeh** [comment]
I have been messing around in bash today learning some new things so I may have messed something up but I dont have any aliases set or anything..

**Comment by ivanthemeh** [comment]
I even tried to set an alias for s and it didnt work :(

**Comment by KeizerDev** [comment]
I think `locate s | grep bin/s` would give you the path of `s`. You should check if it exists and if you can run it using the absolute path

Should wait for @zquestz to answer

**Comment by zquestz** [comment]
First just try `/usr/local/bin/s puppies`.  If that works then there is a `$PATH` issue or an alias hiding somewhere.

**Comment by ivanthemeh** [comment]
Ok so I was able to run it using ```/usr/local/bin/s puppies``` but I am not able to fix it, I tried to add an alias in bash_profile for the line ```/usr/local/bin/s``` and it tells me
