### ISSUE TITLE
Flag which would allow `s` to return URL

### ISSUE THREAD

**Issue by aksr** [zquestz/s#117]
It would be nice if `s` could return URL.
Something like this *could* be useful:

    firefox --new-tab "$(s -u -p wikipedia rhinos)"

(**-u** or **-r** or *whatever* you think is better)

There are other examples.
What do you think?

Best regards.

**Comment by zquestz** [comment]
I think this is a good idea. I will look into it.

**Comment by zquestz** [comment]
Not you can already customize the binary and flags with -b... so you can do:

```
s -b "firefox --new-tab" -p wikipedia rhinos
```

**Comment by aksr** [comment]
Yes, I know, thank you.
Still, I think returning url isn't a bad idea—especially if you're using it *with pipes*.

**Comment by zquestz** [comment]
I went ahead and added an output only mode. You can pass `-o` to only output the URL now. Good suggestion. =)

Also you could have hacked it in before by changing the binary to `echo`. That's what I use for testing, but now I can just use the flag. =)

**Comment by zquestz** [comment]
New 0.5.7 release has this option and is building now. =)

**Comment by aksr** [comment]
Thank you. ;)
