### ISSUE TITLE
s fails silently

### ISSUE THREAD

**Issue by anka-213** [zquestz/s#118]
I know this is not very helpful, but when I try to search with `s`, nothing happens. If I run with `-v`, I get the search url. If I run with `--verson` I get the version `s 0.5.6`. In all cases, exit code 0.

**Comment by zquestz** [comment]
I need more details. What OS are you using? What exact commands are you issuing?

**Comment by anka-213** [comment]
Arch linux. Installed with the aur-package. For example, when running "s
hello", nothing happens.

>

**Comment by zquestz** [comment]
By default `s` uses `xdg-open` to open the URLs. It seems that `xdg-open` does not actually work on your machine but it is very easy to replace the default binary that gets executed.

You can pass in a different binary via the -b flag.
```
s -b "firefox" <search>
```

Or you can adjust the binary permanently through the config file. Just create a file ~/.s/config and include the following:

```
binary: </path/to/binary>
```

**Comment by anka-213** [comment]
Yes, that seems to be the problem. Thank you.
