### ISSUE TITLE
binary file seems too big

### ISSUE THREAD

**Issue by oldratlee** [zquestz/s#125]
I install `s-search` via home brew, **9.4M**.

```bash
$ pwd
/usr/local/Cellar/s-search/0.5.11/bin
$ s --version
s 0.5.11
$ ll
total 9.4M
-r-xr-xr-x 1 jerry admin 9.4M Aug 27 08:57 s*
```

**Comment by zquestz** [comment]
Nope, the binaries in Golang are large because there is also the web server, and several dependencies. This is normal.

**Comment by oldratlee** [comment]
Got.
