### ISSUE TITLE
Have configuration file under ~/.config/s/

### ISSUE THREAD

**Issue by vthiery** [zquestz/s#129]
This

> To setup your own default configuration just create ~/.s/config. 

looks a bit odd. Wouldn't it be better to have in it a more standard way, like `~/.config/s` ?

**Comment by zquestz** [comment]
Well when people setup TLS for the server they generally also have other files in `~/.s`. Figured a directory would be easier for people. I am not tied to it though if we want to change it.

**Comment by vthiery** [comment]
Oh! sorry for the imprecision. The correct path would be `~/.config/s/` which could contain a `config` file and all the necessary files to configure it all.

**Comment by cyrilgdn** [comment]
Interested by that too ! And [loadConfig](https://github.com/zquestz/s/blob/master/cmd/config.go#L51) could support both path  to not break existing installation.
