### ISSUE TITLE
Feature request: Case insensitive providers

### ISSUE THREAD

**Issue by arunsathiya** [zquestz/s#131]
Will it be possible to allow usage of provider keywords like `DuckDuckGo` instead of `duckduckgo`? It would be helpful if providers can be case insensitive.

**Comment by zquestz** [comment]
So this is super simple at the code level, just downcase the provider info before matching it to the plugin list. However, for the autocompletion scripts (zsh, bash, etc), then it would muddy them up quite a bit.

I am happy to accept a PR for the simple down-casing before lookup.

**Comment by zquestz** [comment]
Next release will have this. =)
