### ISSUE TITLE
Customize configuration file path with a command line flag and/or use XDG

### ISSUE THREAD

**Issue by R3load** [zquestz/s#137]
# Customize config file path

By specifying an alternate config file on the command line (like `ssh -F`):

    s --config=/path/to/s/config <query> [flags]

Preferring `$XDG_CONFIG_HOME` as the user config dir, with `~/.config` as fallback:

    $XDG_CONFIG_HOME="/home/$USER/local/cfg" s <query> [flags]

**Comment by zquestz** [comment]
Unfortunately this is not trivial to implement. The configuration file is actually loaded before the flags are parsed. For now I would just symlink the config if you want it another location.

I would be open to a PR for this functionality.
