### ISSUE TITLE
Homebrew

### ISSUE THREAD

**Issue by chrisfinazzo** [zquestz/s#139]
The automated process for updating Homebrew formulas (`brew bump-formula-pr`) fails during its `audit` phase for v0.5.14. Specifically, the use of `go_resource` is now deprecated.  Per the error below, is it possible to implement Go vendoring so that we can pull the latest version automatically?

<img width="585" alt="screen shot 2018-12-22 at 10 33 57 pm" src="https://user-images.githubusercontent.com/1534882/50380593-bde03200-0639-11e9-88aa-9cd36f87bf1c.png">

**Comment by zquestz** [comment]
We can definitely switch to go vendoring. Right now I do like gvt but am open to a PR to change the dependencies. I am pretty sure brew does have hooks to support gvt but not sure exactly how that works.

**Comment by chrisfinazzo** [comment]
I gave this another shot and (per your suggestion) used gvt. However, although I can see the dependencies in `/vendor`, Git currently ignores this file. I presume this should be removed from it and then commited.

In general this seems contradictory to gvt's own documentation which advocates not putting vendored source under versioning, but as I'm not that familiar with Go workflows, I'm a bit lost.

**Comment by zquestz** [comment]
There is no source checked into vendor, just the manifest which is exactly how gvt should work.

**Comment by zquestz** [comment]
Looks like 0.5.14 is now available on Homebrew. Closing.
