### ISSUE TITLE
Cant specify binary using snap

### ISSUE THREAD

**Issue by Julioevm** [zquestz/s#141]
Hey,
I'm trying to use s-search -b w3m but I get the message: executable "w3m" not found in $PATH which it is.
I've also tried to set the config file in .config/s/config with "binary: /usr/bin/w3m"
With no luck, so far. 
Is this a problem of the snap packaged version or am I doing something wrong?

Btw, I've also tried to use firefox instead with no luck, I get the same issue if I try -b with any browser.
Thanks,

**Comment by zquestz** [comment]
Unfortunately snap packages are isolated and can't see your normal path or binaries. This is unsupported at this time. =(
