### ISSUE TITLE
How s search is compared to Surfraw ?

### ISSUE THREAD

**Issue by HiTuX** [zquestz/s#142]
Hi,
I 'm confused if I should use `s` or `surfraw` . There is no comparison elsewhere! 
Could you provide some features of `s` (pros and cons if possible) compared to `surfraw` or other CLI search tools (`ddgr` , `googler` .....)
 
EDIT: typos :(

**Comment by zquestz** [comment]
I prefer `s` but I am biased. ;)

Anyhow, they are quite different, `s` is designed to open your browser, where `surfraw` tries to stay entirely in the terminal. I think people will find them complimentary. =)

**Comment by HiTuX** [comment]
tnx ;)
