### ISSUE TITLE
Passing strings as arguments

### ISSUE THREAD

**Issue by idkjs** [zquestz/s#143]
If you wanted to search github with query params, is that possible?

Some examples:

```
# works with no params
❯ s zquest -p github -o
https://github.com/search?utf8=✓&q=zquest
# doesnt work
❯ s zquestz extension:go -p github -o
https://github.com/search?utf8=✓&q=zquestz+extension%3Ago

# doesnt work with quotes around query string
~
❯ s "zquestz extension:go" -p github -o
https://github.com/search?utf8=✓&q=zquestz+extension%3Ago

# works without `utf8`
~
❯ open https://github.com/search?q=zquestz+extension%3Ago
```

Thanks for sharing your project.

**Comment by zquestz** [comment]
Currently not possible. Right now. it just does a normal search and puts the whole search phrase into the `q` param.

I also. don't see any difference between open https://github.com/search?q=zquestz+extension%3Ago and https://github.com/search?utf8=✓&q=zquestz+extension%3Ago in my testing...

**Comment by idkjs** [comment]
Me neither from your links. I would have to reinstall to see what the issue was. Thanks for taking the time.
