### ISSUE TITLE
How can I search sorted by date?

### ISSUE THREAD

**Issue by bitcoinmeetups** [zquestz/s#167]
Hello,

I'm BM. A very nice and polite guy.

How can I search sorted by date using s?

**Comment by zquestz** [comment]
Duplicate. Closing and tracking in other issue.

**Comment by bitcoinmeetups** [comment]
Try Qwant and Yahoo., they might be easier. DDG and Google would be nice too but not sure if it could be implemented easily with those as they are really trying to prevent users from acquiring this powertool to keep it to themselves.

**Comment by bitcoinmeetups** [comment]
If you implement, where is the other thread? I would really like to follow and get updates.
