### ISSUE TITLE
Use yaml instead of .go files to add providers 

### ISSUE THREAD

**Issue by KeizerDev** [zquestz/s#17]
How about using this. It would be a lot faster to add providers this way. Will start work on it soon if you agree.

**Comment by zquestz** [comment]
Unfortunately probably won't want to do yaml support.

* I like to be able to build the app and ship it as a single binary. With yaml I would have to ship those files as well.
* Not all searches will be the same, some might use different query encodings. So far we have been lucky that everyone has used simple query escaping.

I do like the convenience of text editable providers. I might change my mind later. =)

**Comment by KeizerDev** [comment]
Than add a `optional` or `discussion` tag to it or just close it :wink:

**Comment by zquestz** [comment]
Going to close for now. It already is pretty easy to add providers, and hoping to add bunch more over the next week or so. Should be rarer that people need new ones. =)
