### ISSUE TITLE
Complation - handle blacklist and whitelist

### ISSUE THREAD

**Issue by vantu5z** [zquestz/s#171]
Setting `blacklist` or `whitelist` in config should be handled by complation and `--list-providers`, `--list-tags` params.
For example if we set `whitelist` - provider (tag) complation should work only for this list, also `--list-*` params should return items depending on this list and not on all provider list.

**Comment by zquestz** [comment]
This is great feedback. I agree. Will look into it, or would accept a PR with this change.

**Comment by zquestz** [comment]
It appears that `--list-providers` already works as expected.

`--list-tags` lists all tags, not just from active providers in the latest release. I have pushed a new commit that makes this option provider aware and will push an updated release soon.

I am looking into fixing the completion scripts, that seems more complicated, and might take a bit for me to figure out.

**Comment by zquestz** [comment]
This is all resolved in 0.6.7. Pushing it out now. Thanks for the feedback!

**Comment by vantu5z** [comment]
Thanks for quick response! Works great!
