### ISSUE TITLE
Merge contributor

### ISSUE THREAD

**Issue by KeizerDev** [zquestz/s#26]
I see your timezone is the opposite of mine. I can help you merging the PRs when your not online so we won't get huge merge conflicts. If you inform me correctly what you want with the project and what not I'm pretty sure I can do the job for you if you want. @zquestz

**Comment by zquestz** [comment]
I think that would be great. For now lets just keep it to provider commit merges. For now I don't really want refactors of the other code. That seem sane?

**Comment by zquestz** [comment]
Maybe a -n flag for "native url" and that activates another method on the interface for building the app based uri, and also provide the web version by default?

**Comment by KeizerDev** [comment]
@zquestz Sure! I will just keep my focus on provider commit merges.

**Comment by zquestz** [comment]
Awesome, will add you =)

**Comment by zquestz** [comment]
Done.
