### ISSUE TITLE
Support multiple languages

### ISSUE THREAD

**Issue by linuxundich** [zquestz/s#28]
It would be great if you could configure s to search Google, Wikipedia (and every site which offers more than one language) in a different language than english. Perhaps you could use a config file to save a pre-selection or use a switch like "s foo -lang=de", since -l is already used.

**Comment by zquestz** [comment]
I am going to give thought on how to implement this. Might require a tweak to the provider interface and I want to make sure it is easy for people to implement. Will post some suggestions on this tonight and we will figure it out. I also have plans on localizing the binary itself so you can get errors and help in the appropriate language.

**Comment by zquestz** [comment]
Would something even simpler like locale matching work for your use case? We can pickup the system language, then in the provider use that to determine the correct URI to hit.

**Comment by linuxundich** [comment]
Yes of course, but the possibility to switch the language would still be great.

**Comment by KeizerDev** [comment]
@linuxundich check out my comment on #31

**Comment by p-v** [comment]
@zquestz Any thoughts on this? Providers like amazon become useless unless its specific to a country. The provider has the url `amazon.com` but it can be different for different countries, like `amazon.in` or `amazon.ca`

**Comment by zquestz** [comment]
Yes. I plan on checking the user locale and allowing the provider to case off that. That way if your using a ca locale it will load the correct domain.

**Comment by zquestz** [comment]
Multiple language support is now provided to all providers. They just need to be updated to support the URLs that are needed. The amazon provider has been updated as an example to support amazon.co.uk.
