### ISSUE TITLE
launcher linux: exo-open is xfce specific, use xdg-open

### ISSUE THREAD

**Issue by carlos22** [zquestz/s#3]
Non XFCE Desktops most likley only have xdg-open but not exo-open.
See: https://github.com/zquestz/s/blob/master/launcher/launcher.go#L12

**Comment by advance512** [comment]
Doesn't work on Ubuntu GNOME 15.10, not sure if related.

**Comment by rdark** [comment]
@advance512 - yup. exo-open is XFCE specific. xdg-open is a generic wrapper for gvfs-open(Gnome), kde-open(KDE), or exo-open(XFCE), and will fall back to it's own mime file associations in the case of a stripped down window manager (e.g openbox, awesome etc). It is pretty much guaranteed to be present on all Linux desktops.

**Comment by zquestz** [comment]
Testing this now. Good call.

**Comment by zquestz** [comment]
Done, swapped out and in master. Will cut a release soon.
