### ISSUE TITLE
[Feature Request] custom provider

### ISSUE THREAD

**Issue by FLYSLOW** [zquestz/s#31]
eg: I would like to add https://s.taobao.com/search?q=test for myself via cli.

**Comment by zquestz** [comment]
Yeah right now that is not supported. We are investigating user generated profiles. For now were just accepting PRs and merging them quickly. =)

**Comment by KeizerDev** [comment]
@FLYSLOW Why would you just want to add it for yourself and not just for everyone? Can you give me a use case?

@zquestz It would indeed have been better to use something like a config file where you can put your personal stuff, like the language you want `s` to respond in or so.

**Comment by FLYSLOW** [comment]
@KeizerDev Of course new provider is worthy to add it for everyone, but I don't want to download the package and install it again just for adding a provider. I add a provider for quick use, it doesn't means I will not contribute.

**Comment by zquestz** [comment]
Fair point @FLYSLOW. Still thinking through this, as escaping for custom providers could be more than just QueryParam escaping. Need to think through what this would look like.

**Comment by zquestz** [comment]
Custom providers will be coming soon. Once the configuration file is setup with the existing options in the cli (provider, binary, etc), custom providers will be added. Thanks for the suggestion. =)

**Comment by zquestz** [comment]
Configuration files have been merged as well as provider filtering. Custom providers will be here in the near future!

**Comment by zquestz** [comment]
This was completed in https://github.com/zquestz/s/pull/88
