### ISSUE TITLE
got error inside tmux

### ISSUE THREAD

**Issue by huanzhang** [zquestz/s#47]
The error message is as below:
```
$ s foo
[Error] exit status 1
```

**Comment by zquestz** [comment]
What type of system are you using? Need a bit more info to debug.

**Comment by huanzhang** [comment]
@zquestz I am on OS X EI Capitan 10.11.2

**Comment by zquestz** [comment]
at a terminal can you type "open https://google.com"? All this code does is call the open binary which should be present on all OS X systems.

**Comment by huanzhang** [comment]
I got this:
```
LSOpenURLsWithRole() failed with error -600 for the URL https://google.com.
```

**Comment by zquestz** [comment]
Yeah that is very abnormal. OS X should be able to open any file or url with the open command. Going to look around and see if I can figure out why that happens to you.

**Comment by huanzhang** [comment]
@zquestz forgot to tell you that I am a tmux user

**Comment by zquestz** [comment]
Users have talked about the issue here: http://stackoverflow.com/questions/9750475/api-documentation-lsopenurlswithrole

Does it work outside tmux?

**Comment by zquestz** [comment]
Seems this also happens to Atom users, there is a command they use to fix the issue:
https://github.com/atom/atom/issues/3093 - reattach-to-user-namespace

**Comment by huanzhang** [comment]
@zquestz It works outside tmux:)

**Comment by zquestz** [comment]
You can probably setup an alias if that reattach app works. `alias s="reattach-to-user-namespace s"`

**Comment by zquestz** [comment]
I can confirm tmux on linux works fine, so this is an os x specific issue. Wonder if there is a more general solution.

**Comment by huanzhang** [comment]
@zquestz woow...It works! Thanks.

**Comment by zquestz** [comment]
Fantastic. Glad we found a solution!

**Comment by zquestz** [comment]
http://www.economyofeffort.com/2013/07/29/reattach-to-user-namespace-the-fix-for-your-tmux-in-os-x-woes/
