### ISSUE TITLE
Feature Request: Add debian search

### ISSUE THREAD

**Issue by jkahrs** [zquestz/s#50]
Docs are at:
https://sources.debian.net/doc/api/

**Comment by KeizerDev** [comment]
You can add it yourself, just fork the project and add a new provider.

**Comment by KeizerDev** [comment]
Have a look at https://github.com/zquestz/s/pull/33/files for an example of what to do.

**Comment by jkahrs** [comment]
@KeizerDev  Thy for the example. I'll look into this after FOSDEM

**Comment by zquestz** [comment]
Looking for code search or package search?

**Comment by jkahrs** [comment]
I think i'd split the search into multiple providers.
Like:
"debpackage" (search for package names)
"debfile" (search for package contents/files)
..

**Comment by KeizerDev** [comment]
Sure, PR is welcome :)

**Comment by KeizerDev** [comment]
Will close this for now. Would like to see a PR for this! @jkahrs
