### ISSUE TITLE
[Feature Request] Incognito Mode

### ISSUE THREAD

**Issue by lkhamsurenl** [zquestz/s#57]
I wonder if it's possible to support a flag to specify opening a browser in incognito mode.

**Comment by zquestz** [comment]
Now that is a fantastic idea, will look into it tonight!

**Comment by djap96** [comment]
I think taking arguments for binaries would be great:
"s -b "google-chrome --incognito"  cats
"s -b "firefox --private-window" dogs
"s -b firefox --new-window --safe-mode"  design trends

**Comment by zquestz** [comment]
Doing this tonight for sure!

**Comment by zquestz** [comment]
Binary arguments are now supported, and brought back binary support for windows!

**Comment by lkhamsurenl** [comment]
Oops, sry just saw this. Yep it works beautifully, thanks! With alias, it's very handy and easy to use feature. It might be also nice to add in README how to open incognito in other browsers too.

**Comment by zquestz** [comment]
Feel free to put up a PR with more browser flags. I am finishing up the language/region support. =)
