### ISSUE TITLE
[Feature request] Subreddit search support

### ISSUE THREAD

**Issue by lkhamsurenl** [zquestz/s#65]
It would be nice to search like:
s -p reddit -r cscareerquestions best startups 2016

which would search in reddit.com/r/cscareerquestions "best startups 2016"

**Comment by zquestz** [comment]
I am not a huge fan of custom provider flags, but I think search conventions would work... 

```
s -p reddit /r/cscareerquestions best startups.
```

Then it can match the first phrase, notice it is a subreddit, and then adjust your search. What do you think of a flow more like that?

**Comment by lkhamsurenl** [comment]
That sounds good, I like the format too.  I've created a PR with modified reddit.go with test case:
https://github.com/zquestz/s/pull/66

**Comment by zquestz** [comment]
Closing issue, as this is being merged =)
