### ISSUE TITLE
Create config file for language and locale stuff

### ISSUE THREAD

**Issue by KeizerDev** [zquestz/s#68]
I had this idea to have a config file for `s` just for the language and locale of the searches.
This way we can limit the provider list for each country.  

Like the [dumpert](https://github.com/zquestz/s/tree/master/providers/dumpert) provider is probably never used for a person who isn't dutch and the [arxiv](https://github.com/zquestz/s/tree/master/providers/arxiv) provider vice versa.

For example we can just create something like a config file with the option to show only the providers for a special country like `NL` or `RU` or just simply `ALL`.

For example the config file can look as follow:
```
locale: NL
sitescountry: NL
```
If I want to just search in English I just change the above one or if I only want the list limit to one country I change the bottom one.  

This way we can prevent that the provider list is getting way to big by adding just stuff that no one cares about in some countries and make it still clear. 

Another benefit is that the autocomplete and the `<tab>` support will work a lot better if we have, for example, a lot of Russian sites added. It will be a lot more usefull to use and the list won't be that big this way.

What's your opinion about this?

**Comment by zquestz** [comment]
So I think that doing basic locale filtering is harder for other countries than it seems. I think a better approach is a configuration file that allows you to disable providers. Possibly supporting both whitelist and blacklist approaches.

**Comment by KeizerDev** [comment]
Okay, so, there will be something like a configuration file, right? If so, I'll keep this issue open.

**Comment by zquestz** [comment]
Just a heads up, will be adding a configuration file very soon. This will have the following options:

* whitelist
* blacklist
* provider
* binary
* verbose

Right now I am leaning toward yaml, as json doesn't allow comments.

**Comment by zquestz** [comment]
Actually going to use UCL. =)

**Comment by zquestz** [comment]
All base configurations are now supported in: https://github.com/zquestz/s/pull/86

Will add the whitelist/blacklist support in another PR.

**Comment by zquestz** [comment]
Actually NM, we can leave open till those are done.

**Comment by zquestz** [comment]
Now we can really close this. Both whitelist and blacklist support have been added in https://github.com/zquestz/s/pull/87
