### ISSUE TITLE
[feature request] Match shortest unique initial substring of providers

### ISSUE THREAD

**Issue by placeybordeaux** [zquestz/s#7]
I would like to allow matching providers based off of the shortest unique inital substring of the provider's text.

Example:

```s -p a``` -> ```s -p amazon```
```s -p d``` -> ```d could match digg, dockerhub or duckduckgo```
```s -p duc``` -> ```s -p duckduckgo```

I will most likely implement this in a day or so, just thought I would open an issue for the eventual PR if you want that feature.

**Comment by zquestz** [comment]
This would be fantastic. I was going to do this anyways. =)

**Comment by zquestz** [comment]
Sorry beat you to the punch. Expansion is now supported.
