### ISSUE TITLE
"Command Not Found"

### ISSUE THREAD

**Issue by himynameisdave** [zquestz/s#70]
Yeah I'm new to Go so bear with me. I installed the [Go install stuff](https://golang.org/dl/) and set my `$GOPATH`, then followed the instructions in the readme and I am still getting "command not found" when I try to run it. The make commands appeared to work but idk why the `s` command isn't. I added the `$GOPATH` to my dotfiles, tried a fresh terminal window, but nah.

Doing this on a Mac running El Crappytan.

**Comment by zquestz** [comment]
You need to make sure GOBIN is in your path.

```
export PATH=$GOBIN:$PATH
```
