### ISSUE TITLE
Support homebrew

### ISSUE THREAD

**Issue by samurai20000** [zquestz/s#93]
I would like to install this package via homebrew in OSX.
I'm now working to support this in [here](https://github.com/samurai20000/homebrew/tree/s).

I sent the pull request, and got [2 CI errors](https://github.com/Homebrew/homebrew/pull/49328). 

```
==> audit problems
s:
 * Formula name conflicts with homebrew/emacs/s
 * GitHub repository too new (<30 days old)
```

## Formula name conflicts with homebrew/emacs/s

homebrew official account has [homebrew-emacs](https://github.com/Homebrew/homebrew-emacs) repository to manage the emacs dependencies. The package name 's' is already used in this Formula repository. So, we have to use another name. What name do you want to use to install?

```
$ brew install xxx
```

## GitHub repository too new (<30 days old)

s is quite new project. So I will just wait few days and send pull request again.

**Comment by zquestz** [comment]
So I am open for naming suggestions. Ideally you would think that the current "s" repo would be named "emacs-s" as it has a requirement on emacs. So since the name we want is taken, we need to come up with an alternate name. Then we can use that for other package managers if "s" is not available.

Here are a few I thought of, I definitely am open to suggestions! These are in no particular order.

* s-go
* s-golang
* s-search

As for the new repo, I am sure if you mention that it already has an active userbase and over 1000 stars, they might make an exception. Either that or we wait another week. =)

**Comment by zquestz** [comment]
One other thing, we should try and include the auto completion scripts if we can, those are super useful and the app is much easier to use with those installed.

**Comment by DomT4** [comment]
I'd be happy with `s-search` from Homebrew's point of view, at least.

> As for the new repo, I am sure if you mention that it already has an active userbase and over 1000 stars, they might make an exception. Either that or we wait another week. =)

You're three days off being a month old. We may well reach that point naturally by the time everyone irons out the naming, etc :smile:.

**Comment by zquestz** [comment]
Yeah I still fundamentally think emacs sub packages should be prefixed with emacs, but that is a debate for another day, and people already are actively using that package so it can't change.

I guess s-search isn't so bad, although I doubt people will easily deduce that is the package name if they just hear about "s". Better than nothing I guess. At least I got "s" on the AUR. =P

**Comment by DomT4** [comment]
> and people already are actively using that package so it can't change.

It's not impossible, we have a mechanism to support that. The Emacs tap is very much @dunn's baby though, so I'll defer to him on feelings/thoughts there.

> I doubt people will easily deduce that is the package name if they just hear about "s". 

You could stick various package management installation tips in your `README` or a `PACKAGES` document or something, if you wanted to. That may raise visibility and is a fairly common thing these days.

**Comment by dunn** [comment]
I've been thinking about renaming the Emacs formula (probably to `s-emacs`), but personally I don't think any package should try to claim a one-letter name.

**Comment by zquestz** [comment]
@dunn I think that is fair. I never thought this project would get the traction it did when I was hacking on it on my couch. Funny how something you write for yourself blows up. =)

**Comment by dunn** [comment]
https://github.com/Homebrew/homebrew-emacs/pull/210

**Comment by zquestz** [comment]
@dunn that is awesome. Really appreciate your help on this!

**Comment by zquestz** [comment]
I think we can include docs that "s-search" is the package on package managers where "s" is not available or one-letter repos are not recommended. Then at least the user is only looking for 1 of two options, both of which are called out clearly in the README.md

**Comment by zquestz** [comment]
@DomT4 Thanks for pointing that out. I didn't realize brew had a mechanism for renames!

**Comment by DomT4** [comment]
Do you want us to close the existing one or are you going to push on that branch? Wasn't sure with your wording so thought I'd double check, heh.

**Comment by samurai20000** [comment]
@DomT4 Please close existing pull request. I will make new pull request with the name "s-search". Thanks.

**Comment by DomT4** [comment]
Done, Thanks! Shout if you need any help with the new one.

**Comment by zquestz** [comment]
NIce, thanks @samurai20000 =)

**Comment by zquestz** [comment]
Again a huge thanks. We are now in Homebrew as `s-search`. =)

**Comment by samurai20000** [comment]
I'm glad to help:)
